const ON_USER_LOGGED = 'ON_USER_LOGGED'
const ON_LOAD_ORDERS = 'ON_LOAD_ORDERS'
const ON_ADD_ORDER = 'ON_ADD_ORDER'
const ON_DELETE_ORDER = 'ON_DELETE_ORDER'
const ON_COMPLETE_ORDER = 'ON_COMPLETE_ORDER'
const ON_LOG_OUT = 'ON_LOG_OUT'

export {
  ON_USER_LOGGED,
  ON_LOAD_ORDERS,
  ON_ADD_ORDER,
  ON_DELETE_ORDER,
  ON_COMPLETE_ORDER,
  ON_LOG_OUT
}
